Added black pill board
gl-sergei/chopstx pull request #1
Opened 2018-07-31 13:09 UTC by assasinfil

2018-07-31 19:06 UTC, assasinfil commented
Эту надо добавить первой чтобы пройти проверку в том репозитории

2018-08-01 03:20 UTC, gl-sergei requested changes

2018-08-01 03:20 UTC, gl-sergei commented on board/board-dark-pill.h
> +/* echo -n "Blue Pill" | shasum -a 256 | sed -e 's/^.*\(........\)  -$/\1/' */
Should this command become `echo -n "Dark Pill" | shasum -a 256 | sed -e 's/^.*\(........\)  -$/\1/'` ?

2018-08-01 03:20 UTC, gl-sergei commented on board/board-dark-pill.h
> +#define BOARD_ID    0xa1099d43
and BOARD_ID will be different I guess

2018-08-01 03:20 UTC, gl-sergei commented on board/board-dark-pill.h
> + * PC13 - Push pull output 50MHz (LED 1:ON 0:OFF)
P**B**1**2** - Push pull output 50MHz (LED 1:ON 0:OFF)

2018-08-01 03:20 UTC, gl-sergei commented on board/board-dark-pill.h
> + * PCx  - input with pull-up
P**B**x  - input with pull-up

2018-08-01 03:20 UTC, gl-sergei commented on board/board-dark-pill.h
> +#define RCC_ENR_IOP_EN      (RCC_APB2ENR_IOPBEN | RCC_APB2ENR_IOPCEN)
I think this has to become
#define RCC_ENR_IOP_EN      (RCC_APB2ENR_IOP**A**EN | RCC_APB2ENR_IOP**B**EN)

because we only use GPIOB for LED and GPIOA for USB

2018-08-01 03:20 UTC, gl-sergei commented on board/board-dark-pill.h
> +#define RCC_RSTR_IOP_RST    (RCC_APB2RSTR_IOPARST | RCC_APB2RSTR_IOPCRST)
Same for
#define RCC_RSTR_IOP_RST    (RCC_APB2RSTR_IOP**A**RST | RCC_APB2RSTR_IOP**B**RST)

2018-08-01 08:14 UTC, assasinfil commented
i fixed all

2018-08-01 09:06 UTC, gl-sergei approved these changes
LGTM. Thank you for contribution!

2018-08-01 09:07 UTC, merged

2018-08-01 09:15 UTC, assasinfil commented
Thank you for the project.